services:

##########################################
##
## network infrastructure
##
##########################################

    embaNET-intranet-openvpn:

        container_name: embaNET-intranet-openvpn
        
        image: kylemanna/openvpn

        restart: unless-stopped
                
        cap_add:

            - NET_ADMIN       

        volumes:

            - /volumes/intranet/openvpn:/etc/openvpn

        ports:

            - "1194:1194/udp"

    embaNET-intranet-openvpn-iam:

        container_name: embaNET-intranet-openvpn-iam
        
        image: nginx

        restart: unless-stopped

        volumes:

            - /volumes/intranet/openvpn/:/usr/share/nginx/html/

        ports:

            - "127.0.0.1:1180:80"

##########################################
##
## private desktop
##
##########################################

    embaNET-intranet-desktop:

        container_name: embaNET-intranet-desktop

        hostname: urus

        image: softwareshinobi/shinobi-academy-desktop

        restart: unless-stopped

##        deploy:
##
##            resources:
##
##                limits:
##          - "10.28.1.1:5900:5900"

##                    cpus: 2
##
##                    memory: 3.5G
##
##                reservations:
##
##                    cpus: 1
##
##                    memory: 2.0G

        volumes:

            - /volumes/intranet/desktop/softwareshinobi:/home/softwareshinobi
            
            - /volumes/intranet/media/share:/home/softwareshinobi/Share
            
            - /volumes/intranet/media/:/home/softwareshinobi/Intranet

        ports:

          - "10.28.1.1:5922:22"
          
          - "10.28.1.1:5980:80"

          - "10.28.1.1:5900:5900"

          - "127.0.0.1:5900:5900"
          
        domainname: urus.embanet.softwareshinobi.digital

        environment:
        
            TZ: America/Bogota

            USER_UID: 1000

            USER_GID: 1000

            USER: softwareshinobi

            PASSWORD: shinobi

            HTTP_PASSWORD: shinobi
  
##########################################
##
## file storage
##
##########################################
    
    embaNET-intranet-nfs:

        container_name: embaNET-intranet-nfs

        image: itsthenetwork/nfs-server-alpine:12

        privileged: true
        
        restart: unless-stopped

        volumes:

            - /volumes/intranet/media:/media

        ports:

            - "10.28.1.1:2049:2049"

        environment:

            - SHARED_DIRECTORY=/media

##########################################
##
## office services
##
##########################################

    embaNET-intranet-calendar:

        container_name: embaNET-intranet-calendar

        image: tomsquest/docker-radicale

        restart: unless-stopped

        ports:

            - "10.28.1.1:5232:5232"           

        volumes:

            - /volumes/intranet/calendar:/data

##########################################
##
## relational data
##
##########################################

    embaNET-intranet-database:

        container_name: embaNET-intranet-database

        image: softwareshinobi/embanet-intranet-database

        volumes:

            - /volumes/intranet/database:/var/lib/mysql

        ports:

              - "10.28.1.1:3306:3306"

        environment:

            MYSQL_ROOT_PASSWORD: aggiepride

            MYSQL_DATABASE: aventador

            MYSQL_USER: aventador

            MYSQL_PASSWORD: aventador

    embaNET-intranet-phpmyadmin:

        container_name: embaNET-intranet-phpmyadmin

        image: beeyev/phpmyadmin-lightweight

        depends_on:

           - embaNET-intranet-database

        links:

           - embaNET-intranet-database

        ports:

            - "10.28.1.1:3380:80"

        environment:

            PMA_HOST: embaNET-intranet-database

##########################################
##
## source code control
##
##########################################

    embaNET-intranet-gitea:

        container_name: embaNET-intranet-gitea

        image: gitea/gitea:1.16.8

        restart: unless-stopped

        volumes:

            - /volumes/intranet/gitea:/data

            - /etc/timezone:/etc/timezone:ro

            - /etc/localtime:/etc/localtime:ro

        ports:

            - "10.28.1.1:3000:3000"

            - "10.28.1.1:3022:22"

        environment:

            USER_UID: 1000

            USER_GID: 1000

##########################################
##
## embaNET virfual servers
##
##########################################

    embaNET-intranet-sian:

        container_name: embaNET-intranet-sian

        image: softwareshinobi/software-shinobi-linux

          #        volumes:
          #
          # - /volumes/intranet/sian/shinobi:/home/shinobi
          #
          # - /volumes/intranet/media/share:/home/shinobi/Share
          # 
        hostname: sian

        domainname: sian.embanet.softwareshinobi.digital

        ports:

            - "2222:22"
            
            - "10.28.1.1:4444:22"

##########################################
##
## embassy entertainment
##
##########################################

    embaNET-intranet-emby:

        container_name: embaNET-intranet-emby

        image: emby/embyserver

        hostname: emby

        domainname: radio.vidadeavion.online

        restart: unless-stopped

        volumes:

            - /volumes/intranet/emby:/config

            - /volumes/intranet/media:/media

        ports:

            - "8096:8096"

##########################################
##
## REST APIs & Computing
##
##########################################

    embaNET-intranet-workspace-apis:

        container_name: embaNET-intranet-workspace-apis
        
        image: softwareshinobi/kanban-flow-api:intranet

        depends_on:

           - embaNET-intranet-database
   
        restart: unless-stopped

        ports:

            - "10.28.1.1:8888:8888"

        environment:

            DB_HOST: embaNET-intranet-database

            DB_NAME: prv_kanban_flow

            DB_USER: prv_kanban_flow

            DB_PASS: prv_kanban_flow

##########################################
##
## productivity apps
##
##########################################

    embaNET-intranet-workspace:

        container_name: embaNET-intranet-workspace

        image: softwareshinobi/embanet-intranet-workspace

        ports:

            - "10.28.1.1:5555:80"

    embaNET-intranet-workspace-web:

        container_name: embaNET-intranet-workspace-web

        image: softwareshinobi/kanban-flow-web:intranet

        ports:

            - "10.28.1.1:8880:80"

    article-magick-web:

        container_name: article-magick-web

        image: softwareshinobi/article-magick-web:publicapis

        ports:

            - "10.28.1.1:34080:80"

##########################################
##
## wordpress server
##
##########################################

    embaNET-intranet-wordpress:

        container_name: embaNET-intranet-wordpress

        image: wordpress:latest

        depends_on:

            - embaNET-intranet-database

        restart: unless-stopped
    
        volumes:
                          
            - /volumes/intranet/wordpress:/var/www/html
        
        ports:
        
            - "10.28.1.1:28480:80"        
        
        environment:

            WORDPRESS_DB_HOST: embaNET-intranet-database

            WORDPRESS_DB_USER: prv_wordpress_blog

            WORDPRESS_DB_PASSWORD: prv_wordpress_blog

            WORDPRESS_DB_NAME: prv_wordpress_blog

##########################################
##
## financials reporting
##
##########################################
            
    embaNET-woocommerce-reporting-apis:

        container_name: embaNET-woocommerce-reporting-apis
        
        image: softwareshinobi/embanet-woocommerce-reporting-apis

        restart: unless-stopped

        ports:

            - "10.28.1.1:34888:8888"

        environment:

            DB_HOST: 10.28.1.1:3306

            DB_NAME: prv_wordpress_blog
            
            DB_USER: prv_wordpress_blog

            DB_PASS: prv_wordpress_blog

    embaNET-woocommerce-reporting-web:

        container_name: embaNET-woocommerce-reporting-web

        image: softwareshinobi/embanet-woocommerce-reporting-web

        restart: unless-stopped
        
        ports:

            - "10.28.1.1:34880:80"

    embaNET-woocommerce-reporting-docs:

        container_name: embaNET-woocommerce-reporting-docs

        image: softwareshinobi/embanet-woocommerce-reporting-docs

        restart: unless-stopped
        
        ports:

            - "10.28.1.1:34881:80"
              
