services:

##########################################
##
## public / network infrastructure
##
##########################################

    public-vpn-server:

        container_name: public-openvpn-server
        
        image: kylemanna/openvpn

        restart: unless-stopped
                
        cap_add:

            - NET_ADMIN       

        volumes:

            - /volumes/intranet/openvpn:/etc/openvpn

        ports:

            - "1194:1194/udp"

##########################################
##
## private / identity & access managment
##
##########################################

    private-openvpn-iam:

        container_name: private-openvpn-iam
        
        image: nginx

        restart: unless-stopped

        volumes:

            - /volumes/intranet/openvpn/:/usr/share/nginx/html/

        ports:

            - "127.0.0.1:1180:80"
            
            - "10.28.1.1:1180:80"

##########################################
##
## public / vpn server documentation
##
##########################################

    private-openvpn-docs:

        container_name: private-openvpn-docs

        image: softwareshinobi/embanet-intranet-docs

        build: 

            context: .

            dockerfile: Dockerfile
      
        restart: unless-stopped
  
        ports:

            - "1188:80"

##########################################
##
## vpn traffic / accessible on VPS only
##
##########################################

    private-network-website:

        container_name: private-network-website

        image: softwareshinobi/vpn-server-key-publisher

        restart: unless-stopped
 
        volumes:

            - /tmp/:/tmp/
 
        ports:

            - "127.0.0.1:80:80"
            
            - "10.28.1.1:80:80"
        
